---
- hosts: localhost
  vars_files:
    - vars/run-rsync.yml
    - vars/defaults.yml
  tasks:
    - import_tasks: ../common/assert-kubeconfig.yml
      tags:
      - assert_kubeconfig

    - import_tasks: ../common/assert-vars.yml

    - tags:
      - load_vars
      set_fact:
        pvc_data: "{{ lookup('file', pvc_data_filepath) | from_json }}"

    - name: "debug"
      debug: var=pvc_data


    - name: "Create pod"
      vars:
        pvc_namespace: "{{ item.namespace }}"
        pod_name: "pvc-migrate-pod-{{ (pvc_namespace | hash('md5'))[:10] }}"
        pvcs: "{{ item.pvcs }}"
      include_tasks: tasks/create-pod.yml
      with_items: "{{ pvc_data }}"
