# vars this task expects
#        pvc_namespace: "{{ item.pvc_namespace }}"
#        pvc_name: "{{ item.pvc_name }}"
#        pod_name: "{{ pvc_name }}-ssh-rync"
#        svc_name: "{{ pvc_namespace }}-ssh"
#        volume_name: "{{ item.volume_name }}"
#        secret_name: "{{ pod_name }}-public-key"
#        bound_pod_uid: "{{ item.bound_pod_uid }}"
#        mig_source_host: "{{ item.node_name }}"

- debug: msg="{{ item }}"


- set_fact:
    transfer_pod_wait_retries: 200
    transfer_pod_delete_wait_retries: 200


- name: "Create a pod for rsync"
  k8s:
    state: present
    definition: "{{ lookup('template', 'pod.yml.j2') }}"


- name: "Wait for pod to be running"
  k8s_info:
    api_version: v1
    kind: pod
    name: "{{ pod_name }}"
    namespace: "{{ pvc_namespace }}"
  register: pod
  until: "'Running' in (pod | json_query('resources[].status.phase'))"
  retries: "{{ transfer_pod_wait_retries }}"
  delay: 3


- set_fact:
    failed_pvcs: []
    successful_pvcs: []

- name: "Run rsync for pvc synchronously"
  vars:
    pvc_ns: "{{ item.pvc_namespace }}"
    pvc_name: "{{ item.pvc_name }}"
    volume_name: "{{ item.volume_name }}"
    bound_pod_uid: "{{ item.bound_pod_uid }}"
    node_name: "{{ item.node_name }}"
    pvc_vol_safe_name: "{{ item.pvc_vol_safe_name }}"
  include_tasks: "tasks/rsync.yml"
  with_items: "{{ pvcs }}"


- name: "Cleanup the transfer pod for rsync"
  k8s:
    state: absent
    definition: "{{ lookup('template', 'pod.yml.j2') }}"

- name: "Wait for pod to be deleted"
  k8s_info:
    api_version: v1
    kind: pod
    name: "{{ pod_name }}"
    namespace: "{{ pvc_namespace }}"
  register: p
  until: "{{ p.resources | length == 0 }}"
  retries: "{{ transfer_pod_delete_wait_retries }}"
  delay: 3
